version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: casestudy
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - new
    healthcheck:
      test: pg_isready -U postgres -d casestudy
      interval: 10s
      timeout: 3s
      retries: 5

  parser:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=db"
      - "DB_USER=postgres"
      - "DB_PASS=postgres"
      - "DB_PORT=5433"
      - "DB_NAME=casestudy"
    depends_on:
      db:
        condition: service_started
    restart: on-failure
    networks:
      - new

networks:
  new:
volumes:
  postgres:
